### ISSUE TITLE
(Showcase plugin)] Could not load bundle TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by Tanashwi** [vmware-samples/vcd-ext-samples#75]
**The Showcase Plugin bug**
[44fab20f-75f1-45c4-8f12-a63c18497c2f (Showcase plugin)] Could not load bundle TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at eval (/provider/uiPlugins/44fab20f-75f1-45c4-8f12-a63c18497c2f/84dd6b1f-f06e-4174-8d8b-7bcc28d45f05/bundle.js:1:55219)
    at eval (/provider/uiPlugins/44fab20f-75f1-45c4-8f12-a63c18497c2f/84dd6b1f-f06e-4174-8d8b-7bcc28d45f05/bundle.js:1:55997)
    at Module.eval (/provider/uiPlugins/44fab20f-75f1-45c4-8f12-a63c18497c2f/84dd6b1f-f06e-4174-8d8b-7bcc28d45f05/bundle.js:1:56549)
    at __webpack_require__ (/provider/uiPlugins/44fab20f-75f1-45c4-8f12-a63c18497c2f/84dd6b1f-f06e-4174-8d8b-7bcc28d45f05/bundle.js:1:348)
    at eval (/provider/uiPlugins/44fab20f-75f1-45c4-8f12-a63c18497c2f/84dd6b1f-f06e-4174-8d8b-7bcc28d45f05/bundle.js:1:1427)
    at eval (/provider/uiPlugins/44fab20f-75f1-45c4-8f12-a63c18497c2f/84dd6b1f-f06e-4174-8d8b-7bcc28d45f05/bundle.js:1:1473)
    at a (main.js:1:4213350)
    at main.js:1:4184981
    at C (main.js:1:4185041)

**To Reproduce**
git clone -b showcase-plugin --single-branch https://github.com/vmware-samples/vcd-ext-samples.git
cd vcd-ext-sdk

# install project dependencies
npm ci

# build plugin
npm run build

Then upload the plugin to the vCD portal. Plugin Navigation is not displayed.

**Expected behavior**
Showcase plugin should be displayed under More menu,

**Comment by nvladimirovi** [comment]
Hey @Tanashwi, you may encounter this error because you use Cloud Director version that doesn't support modal/wizard extensibility.

What version of Cloud Director are you using?

**Comment by nvladimirovi** [comment]
Alright, some extension points here are not supported by 10.2, so you have to comment out or exclude all of the classes in the showcase plugin that extend `WizardExtensionComponent`, and you should be good to go.

**Comment by nvladimirovi** [comment]
Closing the issue, re-open if needed.
